"""Extract the first candidate's grasp prefix, without choosing on success."""
import argparse
import hashlib
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pilot", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rows = json.loads((args.pilot / "results.json").read_text())
    args.output.mkdir(parents=True, exist_ok=False)
    for error in (-0.04, 0.0, 0.04):
        row = next(row for row in rows if row["error_x_m"] == error and row["repair_x_m"] == 0)
        if row["process_exit"] != 0 or not row["pilot_branch"]:
            raise ValueError("The preselected source prefix is not available")
        folder = args.pilot / f'branch_{row["id"]:02d}'
        plans = json.loads((folder / "plans.json").read_text())
        protocol = json.loads((folder / "protocol.json").read_text())
        # This fixed task's grasp program has pregrasp and approach motions;
        # opening/closing is generated by the same unchanged native controller.
        if len(plans["left"]) < 2:
            raise ValueError("Missing pregrasp or approach")
        prefix = {"schema": "roborsi.robotwin.frozen-grasp-prefix.v1", "seed": protocol["seed"],
                  "error_x_m": error, "upstream_commit": protocol["upstream_commit"],
                  "source_adapter_commit": protocol["adapter_commit"],
                  "source_plans_sha256": hashlib.sha256((folder / "plans.json").read_bytes()).hexdigest(),
                  "source_prefix_digest": row["pilot_branch"]["prefix_digest"],
                  "source_object_pose": row["pilot_branch"]["audit_only_object_pose"],
                  "source_prefix_steps": row["pilot_branch"]["physics_step"],
                  "selection": "First predeclared continue candidate, irrespective of task success",
                  "left": plans["left"][:2]}
        (args.output / f"error_{round(error * 1000):+d}mm.json").write_text(json.dumps(prefix) + "\n")
        print(json.dumps({"error_x_m": error, "reference_steps": prefix["source_prefix_steps"]}))


if __name__ == "__main__":
    main()
