// MuJoCo evidence is loaded into the same workbench; no page navigation.
(()=>{
const root='../experiments/mujoco/2026-09-23/',section=document.createElement('section');section.id='mujoco';
section.innerHTML=`<h2>MuJoCo · 经典操控任务</h2><p>Fetch Reach、Push、Pick-and-Place。真实 MuJoCo 接触仿真，控制 25 Hz / 物理步长 2 ms；与解析概率沙盒分开报告。</p>
<div class="row"><label>控制器轮次 <select id="physicsPilot"><option value="qualification_heldout">独立资格测试 · 30 场景</option><option value="pilot_003">第三轮 · 抓取保持修正</option><option value="pilot_002">第二轮 · 失败记录</option><option value="pilot_001">第一轮 · 初始控制器</option></select></label></div><div id="physicsQualification" class="scroll"></div><div id="physicsPilotVideos" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px"></div>
<details open><summary>学习型判断器 · 感知策略选择</summary><p class="note">输入是带受控噪声和延迟的状态传感器，不是视觉网络。三个候选共用固定控制器；判断器仅在 episode 开始时选择感知模式。没有调用官方 Jev。</p><div class="row"><select id="physicsSplit"><option value="test">独立测试</option><option value="delay">更长感知延迟</option></select><select id="physicsTask"><option value="FetchPickAndPlace-v4">Pick-and-Place</option><option value="FetchPush-v4">Push</option></select></div><p id="physicsStatus">读取实验结果…</p><div id="physicsMetrics" class="scroll"></div><canvas id="physicsCurve" width="1200" height="260"></canvas><p class="small">曲线：三个训练种子的验证集综合代价；checkpoint 在打开测试集之前确定。成功要求连续 10 个控制周期满足标准目标距离阈值，本次运行在达标后结束。</p><div id="physicsLearnedVideos" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px"></div><p class="small">对照视频固定选择各分布前两个场景，未按成功筛选。完整输入、候选结果、模型预测及录制场景的关节／接触过程均已保存。</p></details>`;
document.getElementById('learned').before(section);const nav=document.querySelector('nav'),a=document.createElement('a');a.href='#mujoco';a.textContent='MuJoCo 经典任务';nav.prepend(a);
const $=id=>document.getElementById(id);let results,trials;
function table(target,head,rows){target.replaceChildren();const t=document.createElement('table');for(const [i,r] of [head,...rows].entries()){const tr=document.createElement('tr');for(const v of r){const td=document.createElement(i?'td':'th');td.textContent=v;tr.append(td)}t.append(tr)}target.append(t)}
function video(target,path,label){const d=document.createElement('div'),v=document.createElement('video'),p=document.createElement('p');v.controls=true;v.preload='metadata';v.src=root+path;p.textContent=label;d.append(v,p);target.append(d)}
async function pilot(){const run=$('physicsPilot').value;const r=await fetch(root+run+'/summary.json');if(!r.ok)throw Error('控制器结果尚未同步');const s=await r.json();table($('physicsQualification'),['任务','曾到达目标','终局成功','最后 10 步保持'],Object.entries(s.metrics).map(([k,v])=>[k,...['ever_success','final_success','sustained_last10'].map(m=>(v[m]*100).toFixed(1)+'% / '+s.episodes.filter(e=>e.task===k).length+' 场景')]));$('physicsPilotVideos').replaceChildren();for(const task of Object.keys(s.metrics))video($('physicsPilotVideos'),(run==='qualification_heldout'?'pilot_003':run)+'/'+task+'.mp4',task+' · 开发集 seed 0 · 真值控制器示例')}
function learned(){if(!results)return;const split=$('physicsSplit').value,task=$('physicsTask').value,s=results.summaries.find(s=>s.split===split);table($('physicsMetrics'),['方法','场景数','成功率','综合代价 ↓','用时 / s','保留 / 快速 / 精确'],Object.entries(s.methods).map(([k,v])=>[k,v[task].episodes,(v[task].success_rate*100).toFixed(1)+'%',v[task].mean_cost.toFixed(4),v[task].duration_s.toFixed(2),v[task].choices.join(' / ')]));$('physicsLearnedVideos').replaceChildren();const idx=task==='FetchPush-v4'?0:1;for(const [method,label] of [['always_keep','保留当前传感器'],['always_accurate','精确但高延迟'],['judge_seed11','判断器 · seed 11']])video($('physicsLearnedVideos'),'judge_001_replay/'+split+'_'+idx+'_'+method+'.mp4',label);$('physicsStatus').textContent='3 个训练种子 · '+results.test_contexts+' 个留出场景 · '+results.candidate_branches+' 个训练／验证／测试候选分支 · 训练设备 '+results.training_device}
function curve(){const ctx=$('physicsCurve').getContext('2d'),w=1200,h=260,values=trials.flatMap(t=>t.curve.map(c=>c.validation_cost)),lo=Math.min(...values)-.02,hi=Math.max(...values)+.02;ctx.clearRect(0,0,w,h);ctx.font='15px system-ui';ctx.fillStyle='#52647b';ctx.fillText('Validation cost',15,24);for(let k=0;k<4;k++){const y=45+k*55,v=hi-(hi-lo)*k/3;ctx.fillText(v.toFixed(3),10,y+5);ctx.strokeStyle='#dce4ee';ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(1160,y);ctx.stroke()}trials.forEach((t,i)=>{ctx.strokeStyle=['#087f78','#b65b12','#7852b0'][i];ctx.lineWidth=2;ctx.beginPath();t.curve.forEach((c,j)=>{const x=70+c.epoch/300*1090,y=45+(hi-c.validation_cost)/(hi-lo)*165;j?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.fillText('seed '+t.seed+' · selected epoch '+t.best_epoch,200+i*290,240)})}
$('physicsPilot').onchange=()=>pilot().catch(e=>$('physicsQualification').textContent=e.message);$('physicsSplit').onchange=learned;$('physicsTask').onchange=learned;
pilot().catch(e=>$('physicsQualification').textContent=e.message);
Promise.all(['results.json','trials.json'].map(f=>fetch(root+'judge_001/'+f).then(r=>{if(!r.ok)throw Error('学习实验正在运行或同步，控制器结果已可查看。');return r.json()}))).then(([r,t])=>{results=r;trials=t;learned();curve()}).catch(e=>$('physicsStatus').textContent=e.message);
})();
