// The checkpoint study stays on the local single-page workbench.
(async()=>{
const base='../experiments/mujoco/2026-09-23/',run=base+'phase_study_001/',replay=base+'phase_audit_001/';
const section=document.createElement('section');section.id='phase';
section.innerHTML=`<h2>新一轮 · 执行中该继续，还是重新看？</h2><p>1,500 个配对检查点 · 4,500 次候选执行 · 12 个模型 · 6,402 参数 / 模型。每个检查点一次决策，使用带噪旧观测和本体状态，无图像编码器、无 GPT 调用。</p><p class="note">长延迟抓取出现局部收益；同分布抓取的阶段查表更强。动作历史的独立收益尚未得到支持。保留负结果，尚不构成主会级创新证明。</p>
<div class="row"><label>分布 <select id="phaseSplit"><option value="test">IID 留出集</option><option value="delay">长延迟留出集</option></select></label><label>任务 <select id="phaseTask"><option value="FetchPickAndPlace-v4">Pick-and-Place</option><option value="FetchPush-v4">Push</option></select></label></div><p id="phaseStatus">读取冻结实验…</p><div id="phaseMetrics" class="scroll"></div>
<details><summary>配对差值与特征消融</summary><p class="small">完整模型三种子的平均代价减去对照；负值更好。按场景 bootstrap 4,000 次，探索性 95% 区间未校正多重比较，也不估计训练种子总体的不确定性。</p><div id="phaseContrasts" class="scroll"></div></details>
<details><summary>全部训练曲线</summary><canvas id="phaseCurve" width="1200" height="310"></canvas><p class="small">颜色对应完整模型 / 去阶段 / 去年龄 / 去历史；每类 3 个种子。仅验证集选 checkpoint。</p></details>
<h3>同一个物理起点 · 三种延续</h3><div class="row"><label>固定展示场景 <select id="phaseCase"></select></label><button id="phasePlay">一起播放</button><button id="phasePause">暂停</button><input id="phaseTime" aria-label="回放时间" type="range" min="0" max="6" step="0.04" value="0"><span id="phaseClock">0.00 s</span></div><p id="phaseDecision"></p><div id="phaseVideos" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px"></div><canvas id="phaseTrace" width="1200" height="250"></canvas><p id="phaseStep" class="small"></p><p class="small">展示场景按任务阶段固定索引选取，没有按成功筛选。30 段视频均与原评测逐步轨迹完全匹配。前缀使用真值控制器，分叉之后只使用规定传感器；不能当作端到端视觉策略成绩。</p>
<details><summary>数据与论文草稿</summary><p>本机保存全部输入、候选结果、模型、训练曲线和选定场景的关节／接触回放。全部 4,500 条原始轨迹另存云端实验归档。</p><div class="row"><a href="${run}frozen_protocol.json">冻结协议</a><a href="${replay}audit.json">全量轨迹审计</a><a href="${replay}replays.json">视频一致性</a><a href="../docs/manuscript/draft_cn.pdf">中文研究稿 PDF</a><a href="../docs/manuscript/README.md">模板与证据范围</a></div></details>`;
document.querySelector('main > nav').after(section);const link=document.createElement('a');link.href='#phase';link.textContent='新：执行中判断';document.querySelector('nav').prepend(link);
const $=id=>document.getElementById(id),names=['继续执行','停住刷新','边动边刷新'],ids=['continue','stop_refresh','async_refresh'],colors=['#59738c','#c1751b','#07877b'];let results,audit,trials,rows={},decisions={},trace,videoEls=[],frameToken=0;
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(url+' 尚未同步');return r.json()}
function table(id,head,rows){const t=document.createElement('table');[head,...rows].forEach((r,i)=>{const tr=document.createElement('tr');r.forEach(v=>{const c=document.createElement(i?'td':'th');c.textContent=v;tr.append(c)});t.append(tr)});$(id).replaceChildren(t)}
function metrics(){const split=$('phaseSplit').value,task=$('phaseTask').value,s=results.summaries.find(v=>v.split===split);const rows=[];for(const key of ['continue','stop_refresh','async_refresh','task_phase_lookup','age_noise_rule','oracle_infeasible']){const v=s.methods[key][task];rows.push([key,v.contexts,(100*v.success_rate).toFixed(1)+'%',v.mean_cost.toFixed(4),v.duration_s.toFixed(2)])}for(const v of audit.variant_means.filter(v=>v.split===split&&v.task===task))rows.push([v.method+' · 3 种子均值',v.contexts,(100*v.success_rate).toFixed(1)+'%',v.mean_cost.toFixed(4),v.duration_s.toFixed(2)]);table('phaseMetrics',['方法','独立场景数','成功率','综合代价 ↓','剩余用时 / s'],rows);const ds=audit.paired_cost_differences.filter(v=>v.split===split&&v.task===task);table('phaseContrasts',['完整模型减去对照','代价差','探索性 95% 区间'],ds.map(v=>[v.comparison.replace('full_mean minus ',''),v.mean.toFixed(5),'['+v.ci95.map(x=>x.toFixed(5)).join(', ')+']']));$('phaseStatus').textContent='每种分布 360 个场景，每任务 180 个；训练种子不重复计入场景数。oracle 使用不可观测的全部候选结果，仅作非部署上界。'}
function cases(){const opts=$('phaseTask').value==='FetchPush-v4'?[[0,'接近 · index 0'],[4,'接触 · index 4']]:[[1,'接近 · index 1'],[5,'闭爪附近 · index 5'],[9,'搬运 · index 9']];$('phaseCase').replaceChildren();for(const [value,label]of opts){const o=document.createElement('option');o.value=value;o.textContent=label;$('phaseCase').append(o)}}
function clock(t){$('phaseClock').textContent=t.toFixed(2)+' s';$('phaseTime').value=t;drawTrace(t);if(trace){$('phaseStep').textContent=trace.branches.map((b,a)=>{const z=b.trace[Math.min(b.trace.length-1,Math.max(0,Math.round(t/.04)-1))];return names[a]+': 阶段 '+z.stage+' / 观测年龄 '+z.sample_age_s.toFixed(2)+' s / 接触数 '+z.contacts+(z.waiting?' / 等待中':'')}).join(' ｜ ')}}
function drawTrace(t=0){if(!trace)return;const c=$('phaseTrace'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const vals=trace.branches.map(b=>b.trace.map(z=>Math.hypot(...z.object.map((v,i)=>v-z.goal[i])))),top=Math.max(.1,...vals.flat());ctx.font='14px system-ui';ctx.fillStyle='#52647b';ctx.fillText('物体到目标距离 / m（评测真值）',14,20);for(let k=0;k<4;k++){const y=40+k*50;ctx.strokeStyle='#dce4ee';ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(1160,y);ctx.stroke();ctx.fillText((top*(1-k/3)).toFixed(2),12,y+5)}vals.forEach((v,a)=>{ctx.strokeStyle=colors[a];ctx.lineWidth=2;ctx.beginPath();v.forEach((d,k)=>{const x=70+(k+1)*.04/6*1090,y=40+(1-d/top)*150;k?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=colors[a];ctx.fillText(names[a],140+a*300,225)});ctx.strokeStyle='#ba435c';ctx.beginPath();ctx.moveTo(70+t/6*1090,30);ctx.lineTo(70+t/6*1090,195);ctx.stroke()}
async function scene(){frameToken++;videoEls.forEach(v=>v.pause());const split=$('phaseSplit').value,index=+$('phaseCase').value,r=rows[split][index];const selected=decisions[split].choices.full_11[index];$('phaseDecision').textContent='seed '+r.context.seed+' · 实际阶段 '+r.stage+' · 刷新延迟 '+(r.context.delay*.04).toFixed(2)+' s · 完整模型 seed 11 选择：'+names[selected];$('phaseVideos').replaceChildren();videoEls=[];ids.forEach((id,a)=>{const div=document.createElement('div'),v=document.createElement('video'),p=document.createElement('p');v.src=replay+split+'_'+index+'_'+id+'.mp4';v.controls=true;v.preload='metadata';p.textContent=names[a]+' · '+(r.success[a]?'成功':'失败')+' · '+r.duration[a].toFixed(2)+' s'+(selected===a?' · 判断器选择':'');div.append(v,p);$('phaseVideos').append(div);videoEls.push(v)});trace=null;const response=await fetch(replay+split+'_'+index+'.json.gz');if(!response.ok)throw Error('场景轨迹未同步');trace=await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).json();clock(0)}
function curves(){const c=$('phaseCurve'),ctx=c.getContext('2d');const values=trials.flatMap(t=>t.curve.map(c=>c.validation_cost)),lo=Math.min(...values),hi=Math.max(...values),cols=['#07877b','#8b5eaa','#c1751b','#4f7fb5'];ctx.clearRect(0,0,c.width,c.height);ctx.font='14px system-ui';for(let k=0;k<4;k++){const y=35+k*60;ctx.fillStyle='#52647b';ctx.fillText((hi-(hi-lo)*k/3).toFixed(3),5,y);ctx.strokeStyle='#dce4ee';ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(1160,y);ctx.stroke()}trials.forEach((t,i)=>{ctx.strokeStyle=cols[Math.floor(i/3)];ctx.globalAlpha=.7;ctx.setLineDash(i%3===0?[]:i%3===1?[6,3]:[2,3]);ctx.beginPath();t.curve.forEach((v,k)=>{const x=70+v.epoch/400*1090,y=35+(hi-v.validation_cost)/(hi-lo)*180;k?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});ctx.globalAlpha=1;ctx.setLineDash([]);['full','no_phase','no_age','no_history'].forEach((t,i)=>{ctx.fillStyle=cols[i];ctx.fillText(t,130+260*i,275)})}
$('phasePlay').onclick=async()=>{const token=++frameToken;await Promise.all(videoEls.map(v=>v.play().catch(()=>{})));const step=()=>{if(token!==frameToken)return;clock(Math.max(...videoEls.map(v=>v.currentTime)));if(videoEls.some(v=>!v.paused&&!v.ended))requestAnimationFrame(step)};step()};$('phasePause').onclick=()=>{frameToken++;videoEls.forEach(v=>v.pause())};$('phaseTime').oninput=e=>{frameToken++;const t=+e.target.value;videoEls.forEach(v=>{v.pause();v.currentTime=Math.min(t,Number.isFinite(v.duration)?Math.max(0,v.duration-.001):t)});clock(t)};
try{[results,audit,trials]=await Promise.all([json(run+'results.json'),json(replay+'audit.json'),json(run+'trials.json')]);for(const split of ['test','delay'])[rows[split],decisions[split]]=await Promise.all([json(run+split+'.json'),json(run+split+'_decisions.json')]);metrics();cases();curves();await scene();if(location.hash==='#phase')section.scrollIntoView({block:'start'});$('phaseSplit').onchange=()=>{metrics();scene().catch(e=>$('phaseDecision').textContent=e.message)};$('phaseTask').onchange=()=>{metrics();cases();scene().catch(e=>$('phaseDecision').textContent=e.message)};$('phaseCase').onchange=()=>scene().catch(e=>$('phaseDecision').textContent=e.message)}catch(e){$('phaseStatus').textContent=e.message}
})();
